### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by JineshShah2001** [geoninja/Uber-Data-Analysis#1]
Hello, I want to get the dataset which you used in your jupyter notebook. I saw your data folder it has some different dataset and not the one you used.Could you please provide me the dataset.

**Comment by geoninja** [comment]
Unfortunately this dataset is no longer available. It was open access when
I used it, but it was available in the cloud so I didn't download it. I
believe you may be able to find something similar at Kaggle though.

Best,
Paula
